# Generated by Django 5.2.3 on 2025-06-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('dayHigh', models.CharField(max_length=20)),
                ('dayLow', models.CharField(max_length=20)),
                ('lastPrice', models.CharField(max_length=20)),
                ('pChange', models.CharField(max_length=20)),
            ],
        ),
    ]
