# Generated by Django 5.2.3 on 2025-06-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercreds',
            name='amount',
            field=models.IntegerField(default=1000000),
        ),
    ]
