# Generated by Django 5.2.3 on 2025-06-25 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_usercreds_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercreds',
            name='password',
        ),
    ]
