# Generated by Django 5.2.3 on 2025-06-27 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_remove_usercreds_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercreds',
            name='amount',
            field=models.FloatField(default=1000000.0),
        ),
        migrations.CreateModel(
            name='StockOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('average_price', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_stocks', to='authorization.usercreds')),
            ],
        ),
    ]
