name: Linting and Coverage Check

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  strict-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 coverage

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run migrations
        run: |
          python manage.py makemigrations --noinput
          python manage.py migrate --noinput

      - name: Run tests with coverage
        run: |
          coverage run manage.py test
          coverage report --fail-under=80
          coverage xml

      - name: Upload coverage to GitHub summary
        if: always()
        run: |
          echo "## Coverage Report" >> $GITHUB_STEP_SUMMARY
          coverage report >> $GITHUB_STEP_SUMMARY