name: Run Django Tests 

on:
  push: 
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Run tests
      env: 
        CI: true
      run: python manage.py test
  