name: Run Migrations 

on:
  push:
    branches: ["*"]
  pull:
    branches: ["*"]

jobs:
  setup-environment:
    runs-on: ubuntu-latest

    steps:
    - name: Run migrations
      run: |
        python manage.py makemigrations --noinput
        python manage.py migrate --noinput